# Links shown under "Elsewhere" in the side column on every page.

- title: Google Scholar
  url: "https://scholar.google.com/citations?user=EYOgO5MAAAAJ"
- title: ORCID
  url: https://orcid.org/0000-0002-6484-4072
- title: GitHub
  url: https://github.com/jehanzebchaudhry
